component Main {
    style root {
        --background-001: url(@asset(../assets/wallpapers/background-001.png));
        --background-002: url(@asset(../assets/wallpapers/background-002.png));
        --background-003: url(@asset(../assets/wallpapers/background-003.png));
        --background-004: url(@asset(../assets/wallpapers/background-004.png));
        --background-005: url(@asset(../assets/wallpapers/background-005.png));
        --background-006: url(@asset(../assets/wallpapers/background-006.png));
        --background-007: url(@asset(../assets/wallpapers/background-007.png));
        --background-008: url(@asset(../assets/wallpapers/background-008.png));
        --background-009: url(@asset(../assets/wallpapers/background-009.png));
        --background-010: url(@asset(../assets/wallpapers/background-010.png));
        --background-011: url(@asset(../assets/wallpapers/background-011.png));
        --background-012: url(@asset(../assets/wallpapers/background-012.png));
        --background-013: url(@asset(../assets/wallpapers/background-013.png));
        --background-014: url(@asset(../assets/wallpapers/background-014.png));
        --background-015: url(@asset(../assets/wallpapers/background-015.png));
        --background-016: url(@asset(../assets/wallpapers/background-016.png));
        --background-017: url(@asset(../assets/wallpapers/background-017.png));
        --background-018: url(@asset(../assets/wallpapers/background-018.png));
        --background-019: url(@asset(../assets/wallpapers/background-019.png));
        --background-020: url(@asset(../assets/wallpapers/background-020.png));
        --background-021: url(@asset(../assets/wallpapers/background-021.png));
        --background-022: url(@asset(../assets/wallpapers/background-022.png));
        --background-023: url(@asset(../assets/wallpapers/background-023.png));
        --background-024: url(@asset(../assets/wallpapers/background-024.png));
        --background-025: url(@asset(../assets/wallpapers/background-025.png));
        --background-026: url(@asset(../assets/wallpapers/background-026.png));
        --background-027: url(@asset(../assets/wallpapers/background-027.png));
        --background-028: url(@asset(../assets/wallpapers/background-028.png));
        --background-029: url(@asset(../assets/wallpapers/background-029.png));
        --background-030: url(@asset(../assets/wallpapers/background-030.png));
        --background-031: url(@asset(../assets/wallpapers/background-031.png));
        --background-032: url(@asset(../assets/wallpapers/background-032.png));
        --background-033: url(@asset(../assets/wallpapers/background-033.png));
        --background-034: url(@asset(../assets/wallpapers/background-034.png));
        --background-035: url(@asset(../assets/wallpapers/background-035.png));
        --background-036: url(@asset(../assets/wallpapers/background-036.png));
        --background-037: url(@asset(../assets/wallpapers/background-037.png));
        --background-038: url(@asset(../assets/wallpapers/background-038.png));
        --background-039: url(@asset(../assets/wallpapers/background-039.png));
        --background-040: url(@asset(../assets/wallpapers/background-040.png));
        --background-041: url(@asset(../assets/wallpapers/background-041.png));
        --background-042: url(@asset(../assets/wallpapers/background-042.png));
        --background-043: url(@asset(../assets/wallpapers/background-043.png));
        --background-044: url(@asset(../assets/wallpapers/background-044.png));
        --background-045: url(@asset(../assets/wallpapers/background-045.png));
        --background-046: url(@asset(../assets/wallpapers/background-046.png));
        --background-047: url(@asset(../assets/wallpapers/background-047.png));
        --background-048: url(@asset(../assets/wallpapers/background-048.png));
        --background-049: url(@asset(../assets/wallpapers/background-049.png));
        --background-050: url(@asset(../assets/wallpapers/background-050.png));
        --background-051: url(@asset(../assets/wallpapers/background-051.png));
        --background-052: url(@asset(../assets/wallpapers/background-052.png));
        --background-053: url(@asset(../assets/wallpapers/background-053.png));
        --background-054: url(@asset(../assets/wallpapers/background-054.png));
        --background-055: url(@asset(../assets/wallpapers/background-055.png));
        --background-056: url(@asset(../assets/wallpapers/background-056.png));
        --background-057: url(@asset(../assets/wallpapers/background-057.png));
        --background-058: url(@asset(../assets/wallpapers/background-058.png));
        --background-059: url(@asset(../assets/wallpapers/background-059.png));
        --background-060: url(@asset(../assets/wallpapers/background-060.png));
        --background-061: url(@asset(../assets/wallpapers/background-061.png));
        --background-062: url(@asset(../assets/wallpapers/background-062.png));
        --background-063: url(@asset(../assets/wallpapers/background-063.png));
        --background-064: url(@asset(../assets/wallpapers/background-064.png));
        --background-065: url(@asset(../assets/wallpapers/background-065.png));
        --background-066: url(@asset(../assets/wallpapers/background-066.png));
        --background-067: url(@asset(../assets/wallpapers/background-067.png));
        --background-068: url(@asset(../assets/wallpapers/background-068.png));
        --background-069: url(@asset(../assets/wallpapers/background-069.png));
        --background-070: url(@asset(../assets/wallpapers/background-070.png));
        --background-071: url(@asset(../assets/wallpapers/background-071.png));
        --background-072: url(@asset(../assets/wallpapers/background-072.png));
        --background-073: url(@asset(../assets/wallpapers/background-073.png));
        --background-074: url(@asset(../assets/wallpapers/background-074.png));
        --background-075: url(@asset(../assets/wallpapers/background-075.png));
        --background-076: url(@asset(../assets/wallpapers/background-076.png));
        --background-077: url(@asset(../assets/wallpapers/background-077.png));
        --background-078: url(@asset(../assets/wallpapers/background-078.png));
        --background-079: url(@asset(../assets/wallpapers/background-079.png));
        --background-080: url(@asset(../assets/wallpapers/background-080.png));
        --background-081: url(@asset(../assets/wallpapers/background-081.png));
        --background-082: url(@asset(../assets/wallpapers/background-082.png));
        --background-083: url(@asset(../assets/wallpapers/background-083.png));
        --background-084: url(@asset(../assets/wallpapers/background-084.png));
        --background-085: url(@asset(../assets/wallpapers/background-085.png));
        --background-086: url(@asset(../assets/wallpapers/background-086.png));
        --background-087: url(@asset(../assets/wallpapers/background-087.png));
        --background-088: url(@asset(../assets/wallpapers/background-088.png));
        --background-089: url(@asset(../assets/wallpapers/background-089.png));
        --background-090: url(@asset(../assets/wallpapers/background-090.png));
        --background-091: url(@asset(../assets/wallpapers/background-091.png));
        --background-092: url(@asset(../assets/wallpapers/background-092.png));
        --background-093: url(@asset(../assets/wallpapers/background-093.png));
        --background-094: url(@asset(../assets/wallpapers/background-094.png));
        --background-095: url(@asset(../assets/wallpapers/background-095.png));
        --background-096: url(@asset(../assets/wallpapers/background-096.png));
        --background-097: url(@asset(../assets/wallpapers/background-097.png));
        --background-098: url(@asset(../assets/wallpapers/background-098.png));
        --background-099: url(@asset(../assets/wallpapers/background-099.png));
        --background-100: url(@asset(../assets/wallpapers/background-100.png));
        --background-101: url(@asset(../assets/wallpapers/background-101.png));
        --background-102: url(@asset(../assets/wallpapers/background-102.png));
        --background-103: url(@asset(../assets/wallpapers/background-103.png));
        --background-104: url(@asset(../assets/wallpapers/background-104.png));
        --background-105: url(@asset(../assets/wallpapers/background-105.png));
        --background-106: url(@asset(../assets/wallpapers/background-106.png));
        --background-107: url(@asset(../assets/wallpapers/background-107.png));
        --background-108: url(@asset(../assets/wallpapers/background-108.png));
        --background-109: url(@asset(../assets/wallpapers/background-109.png));
        --background-110: url(@asset(../assets/wallpapers/background-110.png));
        --background-111: url(@asset(../assets/wallpapers/background-111.png));
        --background-112: url(@asset(../assets/wallpapers/background-112.png));
        --background-113: url(@asset(../assets/wallpapers/background-113.png));
        --background-114: url(@asset(../assets/wallpapers/background-114.png));
        --background-115: url(@asset(../assets/wallpapers/background-115.png));
        --background-116: url(@asset(../assets/wallpapers/background-116.png));
        --background-117: url(@asset(../assets/wallpapers/background-117.png));
        --background-118: url(@asset(../assets/wallpapers/background-118.png));
        --background-119: url(@asset(../assets/wallpapers/background-119.png));
        --background-120: url(@asset(../assets/wallpapers/background-120.png));
        --background-121: url(@asset(../assets/wallpapers/background-121.png));
        --background-122: url(@asset(../assets/wallpapers/background-122.png));
        --background-123: url(@asset(../assets/wallpapers/background-123.png));
        --background-124: url(@asset(../assets/wallpapers/background-124.png));
        --background-125: url(@asset(../assets/wallpapers/background-125.png));
        --background-126: url(@asset(../assets/wallpapers/background-126.png));
        --background-127: url(@asset(../assets/wallpapers/background-127.png));
        --background-128: url(@asset(../assets/wallpapers/background-128.png));
        --background-129: url(@asset(../assets/wallpapers/background-129.png));
        --background-130: url(@asset(../assets/wallpapers/background-130.png));
        --background-131: url(@asset(../assets/wallpapers/background-131.png));
        --background-132: url(@asset(../assets/wallpapers/background-132.png));
        --background-133: url(@asset(../assets/wallpapers/background-133.png));
        --background-134: url(@asset(../assets/wallpapers/background-134.png));
        --background-135: url(@asset(../assets/wallpapers/background-135.png));
        --background-136: url(@asset(../assets/wallpapers/background-136.png));
        --background-137: url(@asset(../assets/wallpapers/background-137.png));
        --background-138: url(@asset(../assets/wallpapers/background-138.png));
        --background-139: url(@asset(../assets/wallpapers/background-139.png));
        --background-140: url(@asset(../assets/wallpapers/background-140.png));
        --background-141: url(@asset(../assets/wallpapers/background-141.png));
        --background-142: url(@asset(../assets/wallpapers/background-142.png));
        --background-143: url(@asset(../assets/wallpapers/background-143.png));
        --background-144: url(@asset(../assets/wallpapers/background-144.png));
        --background-145: url(@asset(../assets/wallpapers/background-145.png));
        --background-146: url(@asset(../assets/wallpapers/background-146.png));
        --background-147: url(@asset(../assets/wallpapers/background-147.png));
        --background-148: url(@asset(../assets/wallpapers/background-148.png));
        --background-149: url(@asset(../assets/wallpapers/background-149.png));
        --background-150: url(@asset(../assets/wallpapers/background-150.png));
        --background-151: url(@asset(../assets/wallpapers/background-151.png));
        --background-152: url(@asset(../assets/wallpapers/background-152.png));
        --background-153: url(@asset(../assets/wallpapers/background-153.png));
        --background-154: url(@asset(../assets/wallpapers/background-154.png));
        --background-155: url(@asset(../assets/wallpapers/background-155.png));
        --background-156: url(@asset(../assets/wallpapers/background-156.png));
        --background-157: url(@asset(../assets/wallpapers/background-157.png));
        --background-158: url(@asset(../assets/wallpapers/background-158.png));
        --background-159: url(@asset(../assets/wallpapers/background-159.png));
        --background-160: url(@asset(../assets/wallpapers/background-160.png));
        --background-161: url(@asset(../assets/wallpapers/background-161.png));
        --background-162: url(@asset(../assets/wallpapers/background-162.png));
        --background-163: url(@asset(../assets/wallpapers/background-163.png));
        --background-164: url(@asset(../assets/wallpapers/background-164.png));
        --background-165: url(@asset(../assets/wallpapers/background-165.png));
        --background-166: url(@asset(../assets/wallpapers/background-166.png));
        --background-167: url(@asset(../assets/wallpapers/background-167.png));
        --background-168: url(@asset(../assets/wallpapers/background-168.png));
        --background-169: url(@asset(../assets/wallpapers/background-169.png));
        --background-170: url(@asset(../assets/wallpapers/background-170.png));
        --background-171: url(@asset(../assets/wallpapers/background-171.png));
        --background-172: url(@asset(../assets/wallpapers/background-172.png));
        --background-173: url(@asset(../assets/wallpapers/background-173.png));
        --background-174: url(@asset(../assets/wallpapers/background-174.png));
        --background-175: url(@asset(../assets/wallpapers/background-175.png));
        --background-176: url(@asset(../assets/wallpapers/background-176.png));
        --background-177: url(@asset(../assets/wallpapers/background-177.png));
        --background-178: url(@asset(../assets/wallpapers/background-178.png));
        --background-179: url(@asset(../assets/wallpapers/background-179.png));
        --background-180: url(@asset(../assets/wallpapers/background-180.png));
        --background-181: url(@asset(../assets/wallpapers/background-181.png));
        --background-182: url(@asset(../assets/wallpapers/background-182.png));
        --background-183: url(@asset(../assets/wallpapers/background-183.png));
        --background-184: url(@asset(../assets/wallpapers/background-184.png));
        --background-185: url(@asset(../assets/wallpapers/background-185.png));
        --background-186: url(@asset(../assets/wallpapers/background-186.png));
        --background-187: url(@asset(../assets/wallpapers/background-187.png));
        --background-188: url(@asset(../assets/wallpapers/background-188.png));
        --background-189: url(@asset(../assets/wallpapers/background-189.png));
        --background-190: url(@asset(../assets/wallpapers/background-190.png));
        --background-191: url(@asset(../assets/wallpapers/background-191.png));
        --background-192: url(@asset(../assets/wallpapers/background-192.png));
        --background-193: url(@asset(../assets/wallpapers/background-193.png));
        --background-194: url(@asset(../assets/wallpapers/background-194.png));
        --background-195: url(@asset(../assets/wallpapers/background-195.png));
        --background-196: url(@asset(../assets/wallpapers/background-196.png));
        --background-197: url(@asset(../assets/wallpapers/background-197.png));
        --background-198: url(@asset(../assets/wallpapers/background-198.png));
        --background-199: url(@asset(../assets/wallpapers/background-199.png));
        --background-200: url(@asset(../assets/wallpapers/background-200.png));
        --background-201: url(@asset(../assets/wallpapers/background-201.png));
        --background-202: url(@asset(../assets/wallpapers/background-202.png));
        --background-203: url(@asset(../assets/wallpapers/background-203.png));
        --background-204: url(@asset(../assets/wallpapers/background-204.png));
        --background-205: url(@asset(../assets/wallpapers/background-205.png));
        --background-206: url(@asset(../assets/wallpapers/background-206.png));
        --background-207: url(@asset(../assets/wallpapers/background-207.png));
        --background-208: url(@asset(../assets/wallpapers/background-208.png));
        --background-209: url(@asset(../assets/wallpapers/background-209.png));
        --background-210: url(@asset(../assets/wallpapers/background-210.png));
        --background-211: url(@asset(../assets/wallpapers/background-211.png));
        --background-212: url(@asset(../assets/wallpapers/background-212.png));
        --background-213: url(@asset(../assets/wallpapers/background-213.png));
        --background-214: url(@asset(../assets/wallpapers/background-214.png));
        --background-215: url(@asset(../assets/wallpapers/background-215.png));
        --background-216: url(@asset(../assets/wallpapers/background-216.png));
        --background-217: url(@asset(../assets/wallpapers/background-217.png));
        --background-218: url(@asset(../assets/wallpapers/background-218.png));
        --background-219: url(@asset(../assets/wallpapers/background-219.png));
        --background-220: url(@asset(../assets/wallpapers/background-220.png));
        --background-221: url(@asset(../assets/wallpapers/background-221.png));
        --background-222: url(@asset(../assets/wallpapers/background-222.png));
        --background-223: url(@asset(../assets/wallpapers/background-223.png));
        --background-224: url(@asset(../assets/wallpapers/background-224.png));
        --background-225: url(@asset(../assets/wallpapers/background-225.png));
        --background-226: url(@asset(../assets/wallpapers/background-226.png));
        --background-227: url(@asset(../assets/wallpapers/background-227.png));
        --background-228: url(@asset(../assets/wallpapers/background-228.png));
        --background-229: url(@asset(../assets/wallpapers/background-229.png));
        --background-230: url(@asset(../assets/wallpapers/background-230.png));
        --background-231: url(@asset(../assets/wallpapers/background-231.png));
        --background-232: url(@asset(../assets/wallpapers/background-232.png));
        --background-233: url(@asset(../assets/wallpapers/background-233.png));
        --background-234: url(@asset(../assets/wallpapers/background-234.png));
        --background-235: url(@asset(../assets/wallpapers/background-235.png));
        --background-236: url(@asset(../assets/wallpapers/background-236.png));
        --background-237: url(@asset(../assets/wallpapers/background-237.png));
        --background-238: url(@asset(../assets/wallpapers/background-238.png));
        --background-239: url(@asset(../assets/wallpapers/background-239.png));
        --background-240: url(@asset(../assets/wallpapers/background-240.png));
        --background-241: url(@asset(../assets/wallpapers/background-241.png));
        --background-242: url(@asset(../assets/wallpapers/background-242.png));
        --background-243: url(@asset(../assets/wallpapers/background-243.png));
        --background-244: url(@asset(../assets/wallpapers/background-244.png));
        --background-245: url(@asset(../assets/wallpapers/background-245.png));
        --background-246: url(@asset(../assets/wallpapers/background-246.png));
        --background-247: url(@asset(../assets/wallpapers/background-247.png));
        --background-248: url(@asset(../assets/wallpapers/background-248.png));
        --background-249: url(@asset(../assets/wallpapers/background-249.png));
        --background-250: url(@asset(../assets/wallpapers/background-250.png));
        --background-251: url(@asset(../assets/wallpapers/background-251.png));
        --background-252: url(@asset(../assets/wallpapers/background-252.png));
        --background-253: url(@asset(../assets/wallpapers/background-253.png));
        --background-254: url(@asset(../assets/wallpapers/background-254.png));
        --background-255: url(@asset(../assets/wallpapers/background-255.png));
        --background-256: url(@asset(../assets/wallpapers/background-256.png));
        --background-257: url(@asset(../assets/wallpapers/background-257.png));
        --background-258: url(@asset(../assets/wallpapers/background-258.png));
        --background-259: url(@asset(../assets/wallpapers/background-259.png));
        --background-260: url(@asset(../assets/wallpapers/background-260.png));
        --background-261: url(@asset(../assets/wallpapers/background-261.png));
        --background-262: url(@asset(../assets/wallpapers/background-262.png));
        --background-263: url(@asset(../assets/wallpapers/background-263.png));
        --background-264: url(@asset(../assets/wallpapers/background-264.png));
        --background-265: url(@asset(../assets/wallpapers/background-265.png));
        --background-266: url(@asset(../assets/wallpapers/background-266.png));
        --background-267: url(@asset(../assets/wallpapers/background-267.png));
        --background-268: url(@asset(../assets/wallpapers/background-268.png));
        --background-269: url(@asset(../assets/wallpapers/background-269.png));
        --background-270: url(@asset(../assets/wallpapers/background-270.png));
        --background-271: url(@asset(../assets/wallpapers/background-271.png));
        --background-272: url(@asset(../assets/wallpapers/background-272.png));
        --background-273: url(@asset(../assets/wallpapers/background-273.png));
        --background-274: url(@asset(../assets/wallpapers/background-274.png));
        --background-275: url(@asset(../assets/wallpapers/background-275.png));
        --background-276: url(@asset(../assets/wallpapers/background-276.png));
        --background-277: url(@asset(../assets/wallpapers/background-277.png));

        min-height: 100vh;
        min-width: 100vw;
        margin: 0; 
        border: 0; 
        padding: 0;
        box-sizing: border-box;

        background-image: var(--#{Wallpaper.selectName()});
        background-size: cover; 
        background-repeat: no-repeat; 
        background-position-x: center;
        background-color: rgba(0, 0, 0, 0.3);

        font-family: 'Inter', sans-serif;
        color: #ddeeee;

        display: flex;
        justify-content: center;
        text-align: center;
    }

    style content {
        width: 820px;
        margin: auto auto;
    }

    style search {
        width: 766px;
        padding: 10px 25px;
        margin-bottom: 25px;
        border-radius: 5px;
        opacity: 90%;
        font-size: 17.5px;
        font-family: 'Inter', sans-serif;
        border: 2px solid #6237a0;
        background-color: #282c34;
        color: #f9ffff;
    }

    fun render : Html {
        // let wallpaper = Wallpaper.select()
        // let path = @asset("/assets/wallpapers/#{wallpaper}")
        // Console.log("WALLPAPER: #{wallpaper}")
        // Console.log("     PATH: #{path}")
        // `document.body.style.backgroundImage = url(#{path})`
        <div::root>
            <div::content>
                <div>
                    <h1>"Startpage"</h1>
                    <input::search type="text" id="search" name="search" placeholder="Search with DuckDuckGo :3"/>
                </div>

                <Content />
            </div>
        </div>
    }
}
